name: Generate Snake Animation
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight
  workflow_dispatch:     # Allows manual runs

permissions:
  contents: write       # Critical for pushing changes

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetches all commit history (important for snk)
          persist-credentials: true

      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: shrutijpg  # Double-check spelling!
          outputs: |
            output/github-contribution-grid-snake.svg
            output/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add output/
          git commit -m "Update snake animation" || echo "No changes to commit"
          git push
